### ISSUE TITLE
go live checklist

### ISSUE THREAD

**Issue by missinglink** [pelias/interpolation#7]
- [x] create a web service interface
- [x] create demo
- [x] dockerize builds
- [x] dockerize server
- [x] improved unit test coverage
- [x] refactor to reduce individual module size
- [x] readme + wikis
- [ ] move automated build process to a production server (https://github.com/pelias/pelias/issues/468)
- [x] write/update blog post

**Comment by missinglink** [comment]
draft blog post written

**Comment by dianashk** [comment]
- [ ] move automated build process to a production server
- [ ] host a production instanced of the demo 
- [ ] add acceptance test framework for this engine
- [ ] what's the deal with security, API keys and rate limits

**Comment by orangejulius** [comment]
There's nothing left to do here that wasn't Mapzen Search specific :tada:
